set nocompatible
syntax on
" set autoindent
execute pathogen#infect()
filetype plugin indent on
:colorscheme badwolf
" :colorscheme desert
" " let mapleader=","
" set runtimepath^=~/.vim/bundle/ctrlp.vim
" set runtimepath^=~/.vim/bundle/nerdtree

call plug#begin()
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()

let g:ctrlp_max_files=50000
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

set rtp^=~/.fzf/plugin/fzf.vim
" runtime fzf.vim
runtime macros/matchit.vim

set showbreak=¬
set winheight=999
set winminheight=0

set laststatus=2
set ruler
set colorcolumn=+1
set textwidth=110
set tb=
" https://github.com/fholgado/minibufexpl.vim.git

" test for usability
noremap <C-J> :bnext<CR>
noremap <C-K> :bprev<CR>
noremap <C-L> :tabn<CR>
noremap <C-H> :tabp<CR>

" use * to search current word in normal mode
nmap * <Plug>AgActionWord
" " use * to search selected text in visual mode
vmap * <Plug>AgActionVisual

noremap <C-Y> :NERDTreeToggle<CR>
noremap <Leader>n :noh<CR>
" let g:reek_always_show = 0

let g:reek_always_show = 0
let g:reek_on_loading = 0

let g:jsx_ext_required = 0

" let g:syntastic_ruby_checkers = ['rubocop', 'reek', 'mri']
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_ruby_checkers = ['rubocop', 'mri']
let g:syntastic_aggregate_errors = 1
let g:syntastic_ruby_reek_exec = 'bundle exec reek'
let g:syntastic_ruby_rubocop_exec      = '/home/afa/.rbenv/shims/rubocop'
" let g:syntastic_ruby_rubocop_exec = 'bundle exec rubocop'

let g:startify_list_order = ['sessions', 'files', 'dir', 'bookmarks']
let g:startify_session_persistence = 1

autocmd User Startified setlocal buftype=

    " url = https://github.com/rking/ag.vim
    " url = https://github.com/vim-scripts/badwolf.git
    " url = https://github.com/kien/ctrlp.vim.git
    " url = https://github.com/scrooloose/nerdtree.git
    " url = https://github.com/vim-syntastic/syntastic.git
    " url = https://github.com/jgdavey/tslime.vim.git
    " url = git://github.com/tpope/vim-bundler.git
    " url = https://github.com/kchmck/vim-coffee-script.git
    " url = git://github.com/tpope/vim-commentary.git
    " url = https://github.com/elixir-lang/vim-elixir.git
    " url = git://github.com/tpope/vim-fugitive.git
    " url = https://github.com/elzr/vim-json.git
    " url = https://github.com/isa/vim-matchit.git
    " url = git://github.com/tpope/vim-rails.git
    " url = https://github.com/rainerborene/vim-reek.git
    " url = https://github.com/taq/vim-refact.git
    " url = https://github.com/thoughtbot/vim-rspec.git
    " url = https://github.com/ngmy/vim-rubocop.git
    " url = git://github.com/slim-template/vim-slim.git
    " url = https://github.com/mhinz/vim-startify

