set nocompatible
syntax on
" set autoindent
execute pathogen#infect()
filetype plugin indent on

map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

:colorscheme badwolf
runtime macros/matchit.vim

set showbreak=¬
set winheight=999
set winminheight=0

" https://github.com/fholgado/minibufexpl.vim.git

" test for usability
noremap <C-J> :bnext<CR>
noremap <C-K> :bprev<CR>
noremap <C-L> :tabn<CR>
noremap <C-H> :tabp<CR>

noremap <C-Y> :NERDTreeToggle<CR>
noremap <Leader>n :noh<CR>
" let g:reek_always_show = 0

" use * to search current word in normal mode
nmap * <Plug>AgActionWord
" " use * to search selected text in visual mode
vmap * <Plug>AgActionVisual

let g:startify_list_order = ['sessions', 'files', 'dir', 'bookmarks']
let g:startify_session_persistence = 1
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

" set rtp+=~/.vim/bundle/vim-project/
" let g:project_use_nerdtree = 1
" call project#rc("~/rails")
" Project "sc/simple_api_tester", "infoapi"
" Project "sc/index_api", "indexapi"
" Project "afalone", "afalone"
" Project "ld_auto", "maploader"
" Project "sc/pictie", "pictie"
